### PR TITLE
Finally making the plugin pipeline ready

### PR DESCRIPTION
**Pull request by fordperfect78**

### CODE REVIEW

**Comment by elordahl** [comment]
Is it possible, with pipelines, to have a Jenkins job use Checkmarx to scan a branch in addition to **another job** which will build that same branch?  I have considered tying the Checkmarx step to logic based on the **type** of trigger (nightly polling vs. hooks), but that seems sloppy.

For context, some of our scans take hours, and so running them against each commit is not ideal.  Instead, we have an ad-hoc job configured to run each night if new commits have been pushed.  I'd like to keep this functionality in tact with pipelines, but am trying to determine if it's possible from a single `Jenkinsfile`.

**Comment by elordahl** [comment]
@fordperfect78 Do you have any thoughts?

**Comment by fordperfect78** [comment]
Hi Eric,

since you are able to specify which files are zipped and uploaded for
scanning as well as the project to upload to, you should theoretically be
able to do several scans within a single Jenkinsfile.

With best regards,
Sven

Am 05.01.2017 17:23 schrieb "Eric Lordahl" <notifications@github.com>:

**Comment by fordperfect78** [comment]
Hi Eric,
after reading it again I am still not sure if I got your point. You want a Jenkinsfile to do the Checkmarx scan and depending on the outcome of that trigger another Jenkins Job that does the build?

Triggering another job could i.e. be done using sh and cURL and Jenkins REST API.

Perhaps you can clarify a bit.

Thanks,
Sven

**Comment by elordahl** [comment]
Hey Sven, 

I'm looking to cover two use-cases in a single `Jenkinsfile`:

1.  Build every commit to a branch **without** running Checkmarx scans.
2. Once per week, run the build **and** invoke the Checkmarx scan.

Does that clarify my needs?  Thanks! 
Eric

**Comment by alanranciato** [comment]
What about scheduling the frequency of the run in the same fashion as the cron scheduling on a standard trigger.  Date math from the last time the scan ran?  Set the parameter in the Jenkinsfile for the time trigger?

**Comment by alanranciato** [comment]
Any chance we could get that in an RFE though - and possible see this merged?  This looks awesome.  Would love to get my hands on it (officially).

**Comment by fordperfect78** [comment]
Hi Eric,
that clarifies it, thanks. Up to now I have only run a Jenkinsfile Pipeline build on each commit, so I am lacking experience on manually triggering it but from my understanding you should be able to parameterize whether you invoke the Checkmarx step or not and define the not case as default behavior using groovy.
Best regards,
Sven

**Comment by elordahl** [comment]
**Thanks** guys.  It sounds like putting logic around multiple triggers, and only invoking Checkmarx when the polling-trigger is used is the only route to accomplish this.

**Comment by filipre** [comment]
What's the status of the PR? Is it going to be merged soon? Pipeline support would be really nice.

**Comment by NeverOddOrEven** [comment]
+1, would also like to use jenkins pipeline to invoke scans on commit changes.

**Comment by yermulnik** [comment]
Is there any chance for tjis pull request to be merged?

**Comment by NeverOddOrEven** [comment]
The project does support pipeline now: https://checkmarx.atlassian.net/wiki/pages/viewpage.action?pageId=128238653

**Comment by yermulnik** [comment]
@NeverOddOrEven Thanks! Missed that update!

**Comment by NeverOddOrEven** [comment]
@yermulnik You're welcome, happy to help!

**Comment by fordperfect78** [comment]
Hi guys, I checked the code once more. They implemented it on their own.
The plug in is pipeline enabled. Have fun!

Am 22.05.2017 4:36 nachm. schrieb "George L. Yermulnik" <
notifications@github.com>:

**Comment by fordperfect78** [comment]
Has been implemented in the meanwhile, therefore this request is obsolete.

**Pull request closed without merging**
