### PR TITLE
Fix Bug 252489: [Jenkins] - Failed with error CxUrlOrigin more than15…

### PR DESCRIPTION
**Pull request by margaritalm**
…0 characters

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by SubhadraSahoo — APPROVED** [review]
Looks good.

**Comment by daniel-beck** [comment]
Just in case it's unintentional: the release exists on GitHub but has not been published to the Jenkins project Maven repo, so users will not be able to download the update through the update center in Jenkins.

**Comment by sf-riqbal** [comment]
@SubhadraSahoo Any ETA on when this version will be available in Jenkins Update center?

**Comment by daniel-beck** [comment]
`checkmarx-2021.4.3` is out 🎉

**Pull request merged**
