### PR TITLE
set results to environment variables

### PR DESCRIPTION
**Pull request by elordahl**
This allows for simple customization of notifications in other plugins and build steps.

### CODE REVIEW

**Comment by sergeykad** [comment]
Hi Eric,
thanks for the pull request.

However, some changes should be made before it can be merged:

- Change the prefix from "CX_VULNS_FOUND_" to "CXSAST_RESULTS_".
- Extract VarEnvAction class to a separate file and rename to EnvVarAction.
- Apply formatting.
- Remove null checks.
- Move all the logic into the EnvVarAction class, so CxScanBuilder will only have something like this:
``` Java
EnvVarAction envVarAction = new EnvVarAction();
envVarAction.setCxSastResults(cxScanResult);
build.addAction(envVarAction);
```

**Comment by elordahl** [comment]
* ~~Change the prefix from "CX_VULNS_FOUND_" to "CXSAST_RESULTS_".~~
* ~~Extract VarEnvAction class to a separate file and rename to EnvVarAction.~~
* Apply formatting.
* Remove null checks.
* ~~Move all the logic into the EnvVarAction class~~

@sergeykad What sort of formatting would you like?  and why do you want the null checks removed?

**Comment by elordahl** [comment]
Note: I will squash commits prior to merge.

**Comment by sergeykad** [comment]
The null checks are redundant, since the variables cannot be null.

**Comment by elordahl** [comment]
Null checks removed and commits squashed.  Let me know if there is anything else.  :+1:

**Comment by sergeykad** [comment]
Looks good. We will merge it.

**Comment by elordahl** [comment]
Any chance this can be merged in next version?  🙏

**Pull request merged**
